USE [master]
GO

/****** Object:  Database [onlineShopSWP]    Script Date: 9/30/2022 10:17:28 AM ******/
CREATE DATABASE [onlineShopSWP]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'onlineShopSWP', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\onlineShopSWP.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'onlineShopSWP_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\onlineShopSWP_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [onlineShopSWP] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [onlineShopSWP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [onlineShopSWP] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [onlineShopSWP] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [onlineShopSWP] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [onlineShopSWP] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [onlineShopSWP] SET ARITHABORT OFF 
GO

ALTER DATABASE [onlineShopSWP] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [onlineShopSWP] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [onlineShopSWP] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [onlineShopSWP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [onlineShopSWP] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [onlineShopSWP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [onlineShopSWP] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [onlineShopSWP] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [onlineShopSWP] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [onlineShopSWP] SET  ENABLE_BROKER 
GO

ALTER DATABASE [onlineShopSWP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [onlineShopSWP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [onlineShopSWP] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [onlineShopSWP] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [onlineShopSWP] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [onlineShopSWP] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [onlineShopSWP] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [onlineShopSWP] SET RECOVERY FULL 
GO

ALTER DATABASE [onlineShopSWP] SET  MULTI_USER 
GO

ALTER DATABASE [onlineShopSWP] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [onlineShopSWP] SET DB_CHAINING OFF 
GO

ALTER DATABASE [onlineShopSWP] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [onlineShopSWP] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [onlineShopSWP] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [onlineShopSWP] SET QUERY_STORE = OFF
GO

USE [onlineShopSWP]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [onlineShopSWP] SET  READ_WRITE 
GO


